### ISSUE TITLE
6/8 time scores should be displayed differently

### ISSUE THREAD

**Issue by remcohh** [montulli/GrooveScribe#17]
First of all I really like your project!
After playing a bit I have one remark.
I think rhythms in 6/8 are not displayed like it should
Notes are grouped by 2 by 2 but 6/8 is counted as 123-123
so when you set it to 8th notes, there should be 2 groups of three instead of 3 groups of 2

Cheers,
Remco

**Comment by montulli** [comment]
I think this works now.  https://goo.gl/GqEd8E
