### ISSUE TITLE
Not possible to mix triplets and non-triplet in a single count

### ISSUE THREAD

**Issue by PxT** [montulli/GrooveScribe#19]
It doesn't seem possible to express triplets and non-triplets in a single count.  i.e. for the single stroke four rudiment you would typically write three 16th note triplets followed by an eighth note all within count 1.  

I think the ratamacue rudiments would also be impossible to notate currently, for the same reason, even if #5 is fixed.  Ideally the parent bug to this should be "support notating all 40 rudiments".  

The fix seems difficult because of the way isTripletDivision works.  The single stroke four has 16 notes per measure…

Anyway, cool project, I just discovered it.  I've been using VexFlow to notate things on one of my sites for a while but this could potentially make my life easier.  👍

**Comment by montulli** [comment]
On the left side choose 'Mixed Division'.  That will show you a matrix of 12 notes per beat.   You can then do 16th notes and 16th note triplets combined.   

https://goo.gl/om1nU1

**Comment by montulli** [comment]
It would be a great goal to try to support all 40 rudiments.   I think we should close this bug and open a specific bug for features required to support specific rudiments.
