### ISSUE TITLE
Wrong link in about file

### ISSUE THREAD

**Issue by Ray-Eldath** [montulli/GrooveScribe#20]
The about link in [Groove Scribe](https://www.mikeslessons.com/groove/gscribe_about.html) is in wrong format...
![snipaste_2018-12-16_01-55-11](https://user-images.githubusercontent.com/7938763/50045910-aa7f1500-00d5-11e9-841c-ccfd01090e5d.png)
it should be
```html
<a href="https://github.com/montulli/GrooveScribe">GitHub</a>
```

**Comment by montulli** [comment]
thanks for the report.  Fixed
