### ISSUE TITLE
Add toms

### ISSUE THREAD

**Issue by montulli** [montulli/GrooveScribe#3]
Simple: 1 rack tom, 1 floor tom. Medium: 2 rack toms, 2 floor toms Complex: Lots o' toms (Terry Bozzio style)

**Comment by montulli** [comment]
Done.   Just 1 rack and 1 floor.   Could do more, but the UI would be crazy complex.

**Comment by MDJLengers** [comment]
A basic drumkit has 3 toms. Can you please at one more? is it also possible to give the toms another notehead? like a open note with a cross in it?

**Comment by montulli** [comment]
I don't disagree with you about 3 toms, but I doubt it is something that will be done soon.    We are looking at some UI changes in the future, so we will see if that is something that can be added.    The backend code supports up to 4 toms, but he UI does not yet.

**Comment by MDJLengers** [comment]
Thank you very much for answering my question. I really like the app. Is it possible to join you building the app? I’m a drumteatcher with knowhow  of css and html. I like to learn more of your code. Is the sourcecode availble for downloading?

I like to here of you,

Greeting Jorrit from the netherlands



Van: Lou Montulli [mailto:notifications@github.com]
Verzonden: woensdag 27 februari 2019 22:44
Aan: montulli/GrooveScribe <GrooveScribe@noreply.github.com>
CC: MDJLengers <jorritlengers@hotmail.com>; Comment <comment@noreply.github.com>
Onderwerp: Re: [montulli/GrooveScribe] Add toms (#3)


I don't disagree with you about 3 toms, but I doubt it is something that will be done soon. We are looking at some UI changes in the future, so we will see if that is something that can be added. The backend code supports up to 4 toms, but he UI does not yet.
