### ISSUE TITLE
Download as png feature not working

### ISSUE THREAD

**Issue by Tamatushi** [montulli/GrooveScribe#30]
Hi,
I’ve tried using the download as png feature in the web app on my android phone and also using the iPad app on my iPad Air. On the android phone the image saves black notation on a black background such that the notation cannot be read. On the iPad an error pops up saying save to png has failed. Please could you advise as to how to make this work on either device, or if you have time please could you look at whether a fix can be implemented?
Thanks for your help, Alex

**Comment by leocaseiro** [comment]
Interesting, I was able to replicate this issue (even though it works fine on desktop).

Workaround:
On iPhone, I was able to use the print feature, and save it as a PDF. (It is not a png, but it might suit you).
Alternatively, you can screenshot the view mode and the mobile will save it as an image, not always perfect, but if you position the browser correctly, it might just work.

Again, these are just workarounds.

**Comment by montulli** [comment]
This is probably something that can be fixed with a style sheet.  Try this:

`
@media print {
  body {
    background-color: white !important;
  }
}
`

**Comment by montulli** [comment]
The PNG has a transparent background on purpose so that the image can be embedded into a document with any light colored background.   The image viewer you are using is defaulting to a black background which is not ideal for looking at a transparent PNG with black text.
