### ISSUE TITLE
Volume feature

### ISSUE THREAD

**Issue by ikrolo** [montulli/GrooveScribe#32]
Hi, would it be possible to add a Volume slider function?  I like having this on in the background with just the metronome sometimes even and turning it down a lot.  Works well for big conference calls and such and rudiments training :)  Currently I end up using Windows Volume Mixer to turn down Chrome volume dramatically.  Thanks

**Comment by montulli** [comment]
Sorry, not enough demand for this feature.   Your current solution is probably the best.
