### ISSUE TITLE
Fix Code Quality issues raised by SonarCloud?

### ISSUE THREAD

**Issue by agigleux** [montulli/GrooveScribe#37]
Hello,

I analyzed your repo with [SonarCloud](https://sonarcloud.io/) as I was curious to know the potential issues you may have before subscribing to https://www.mikeslessons.com/. You can do it yourself also, because it's free for open-source projects.

I believe there is a couple of [Bugs](https://sonarcloud.io/project/issues?id=agigleux_GrooveScribe&resolved=false&types=BUG) and [Blocker Code Smells](https://sonarcloud.io/project/issues?id=agigleux_GrooveScribe&resolved=false&severities=BLOCKER&types=CODE_SMELL) to look at.

Here are some samples of what is detected:

![image](https://user-images.githubusercontent.com/1057037/136563456-dd280b79-26d2-4554-8d41-38898432a269.png)

![image](https://user-images.githubusercontent.com/1057037/136563503-a17422b4-7a39-492e-84ee-a0de969b2282.png)

Alex

**Comment by montulli** [comment]
The warnings that it has found are not bugs.  They could be removed but yhey are there for code consistency even though they will never execute.
