### ISSUE TITLE
Request: Ride and other cymbals?

### ISSUE THREAD

**Issue by aaronsnoswell** [montulli/GrooveScribe#41]
Hello :) I'd love to be able to add the ride cymbal to my grooves - other cymbals too potentially, but mostly the ride.

**Comment by leocaseiro** [comment]
Try right click on the hi-hat and selecting other cymbals.


![](http://g.recordit.co/mhBT4XVaij.gif)


PS: The edit mode doesn't work on mobile (Issue #42)

**Comment by aaronsnoswell** [comment]
Oh wow. I did not know this feature existed!

Thank you!
