### ISSUE TITLE
Context Menu is not working in iPhone - suggestion to fix with force press

### ISSUE THREAD

**Issue by leocaseiro** [montulli/GrooveScribe#42]
Hi there, I'm not sure what is the coverage for Android for contextmenu, but it doesn't work at all for iPhone.

I was wondering if it would be okay for me to implement a pressure touch using the `pressure.js` ?

https://pressurejs.com/ (See example "5: Deep or Force Press").

**Comment by montulli** [comment]
The 'advanced edit' button is used to access all the context menus so that long press is not needed.
