### ISSUE TITLE
Add metronome speed increase by set amount per bars played

### ISSUE THREAD

**Issue by sizzleweet** [montulli/GrooveScribe#43]
Not sure if this is the right place to do this, but I was hoping to make a feature request regarding the metronome.

I was hoping that you could add the functionality that basically every "X" amount of bars increase bpm by "Y" bpm from a starting bpm to an ending one.

i.e. 

Every 2 bars increase bpm by 5.  From 80 bpm to 120 bpm.

Bonus points if you can even do decreasing bpm and rhythm training I.e. metronome/beat on and off every X amount of bars.
Thanks!

**Comment by montulli** [comment]
There is already an 'auto speed up' feature.   Look under Metronome -> options.  It is based on time instead of bars.
